<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>ToolboxFileEmbedding</groupId>
  <artifactId>ToolboxFileEmbedding</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <build>
    <sourceDirectory>lib/src/main/java</sourceDirectory>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-resources-plugin</artifactId>
        <version>3.3.1</version>
        <configuration>
          <encoding>UTF-8</encoding>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.13.0</version>
        <configuration>
          <source>1.8</source>
          <target>1.8</target>
          <encoding>UTF-8</encoding>
          <compilerArgs>
            <arg>-Xlint:-options</arg>
            <!-- Suppresses the bootstrap warning -->
          </compilerArgs>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.5.0</version>
        <configuration>
          <mainClass>ToolboxFileEmbedding.ToolboxFileEmbedding</mainClass>
        </configuration>
      </plugin>
    </plugins>
  </build>

  <dependencies>
    <dependency>
      <groupId>com.pdftools</groupId>
      <artifactId>toolbox</artifactId>
      <version>1.12.0</version>
    </dependency>
  </dependencies>
  <profiles>
    <profile>
      <id>windows-x64</id>
      <activation>
        <os>
          <family>windows</family>
          <arch>x86_64</arch>
        </os>
      </activation>
      <dependencies>
        <dependency>
          <groupId>com.pdftools</groupId>
          <artifactId>toolbox</artifactId>
          <version>1.12.0</version>
          <classifier>win-x64</classifier>
          <type>dll</type>
          <scope>runtime</scope>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>windows-amd64</id>
      <activation>
        <os>
          <family>windows</family>
          <arch>amd64</arch>
        </os>
      </activation>
      <dependencies>
        <dependency>
          <groupId>com.pdftools</groupId>
          <artifactId>toolbox</artifactId>
          <version>1.12.0</version>
          <classifier>win-x64</classifier>
          <type>dll</type>
          <scope>runtime</scope>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>windows-x86</id>
      <activation>
        <os>
          <family>windows</family>
          <arch>x86</arch>
        </os>
      </activation>
      <dependencies>
        <dependency>
          <groupId>com.pdftools</groupId>
          <artifactId>toolbox</artifactId>
          <version>1.12.0</version>
          <classifier>win-x86</classifier>
          <type>dll</type>
          <scope>runtime</scope>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>windows-arm64</id>
      <activation>
        <os>
          <family>windows</family>
          <arch>aarch64</arch>
        </os>
      </activation>
      <dependencies>
        <dependency>
          <groupId>com.pdftools</groupId>
          <artifactId>toolbox</artifactId>
          <version>1.12.0</version>
          <classifier>win-arm64</classifier>
          <type>dll</type>
          <scope>runtime</scope>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>linux-x64</id>
      <activation>
        <os>
          <family>unix</family>
          <arch>x86_64</arch>
        </os>
      </activation>
      <dependencies>
        <dependency>
          <groupId>com.pdftools</groupId>
          <artifactId>toolbox</artifactId>
          <version>1.12.0</version>
          <classifier>linux-x64</classifier>
          <type>so</type>
          <scope>runtime</scope>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>linux-amd64</id>
      <activation>
        <os>
          <family>unix</family>
          <arch>amd64</arch>
        </os>
      </activation>
      <dependencies>
        <dependency>
          <groupId>com.pdftools</groupId>
          <artifactId>toolbox</artifactId>
          <version>1.12.0</version>
          <classifier>linux-x64</classifier>
          <type>so</type>
          <scope>runtime</scope>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>linux-x64-glibc2.12</id>
      <activation>
        <os>
          <family>unix</family>
          <arch>x86_64</arch>
        </os>
      </activation>
      <dependencies>
        <dependency>
          <groupId>com.pdftools</groupId>
          <artifactId>toolbox</artifactId>
          <version>1.12.0</version>
          <classifier>linux-x64-glibc2.12</classifier>
          <type>so</type>
          <scope>runtime</scope>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>linux-arm64</id>
      <activation>
        <os>
          <family>unix</family>
          <arch>aarch64</arch>
        </os>
      </activation>
      <dependencies>
        <dependency>
          <groupId>com.pdftools</groupId>
          <artifactId>toolbox</artifactId>
          <version>1.12.0</version>
          <classifier>linux-arm64</classifier>
          <type>so</type>
          <scope>runtime</scope>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>osx-x64</id>
      <activation>
        <os>
          <family>mac</family>
          <arch>x86_64</arch>
        </os>
      </activation>
      <dependencies>
        <dependency>
          <groupId>com.pdftools</groupId>
          <artifactId>toolbox</artifactId>
          <version>1.12.0</version>
          <classifier>osx-x64</classifier>
          <type>dylib</type>
          <scope>runtime</scope>
        </dependency>
      </dependencies>
    </profile>
    <profile>
      <id>osx-arm64</id>
      <activation>
        <os>
          <family>mac</family>
          <arch>aarch64</arch>
        </os>
      </activation>
      <dependencies>
        <dependency>
          <groupId>com.pdftools</groupId>
          <artifactId>toolbox</artifactId>
          <version>1.12.0</version>
          <classifier>osx-arm64</classifier>
          <type>dylib</type>
          <scope>runtime</scope>
        </dependency>
      </dependencies>
    </profile>
  </profiles>
</project>